---
# file: roles/develop/tasks/htppd.yml
- name: be sure httpd is installed
  yum: name=httpd state=installed
  tags: httpd
- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes
  tags: httpd
- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="80"
    insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 80 -j ACCEPT"
  notify:
  - restart iptables
  tags: httpd
